import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Headline } from "../components/Headline";
import { Footer } from "../components/Footer";
import { Links } from "../components/Links";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Headline page='about' />

        <Links />
      </main>
      <Footer />

      <Footer />
    </div>
  );
}
